name: URLChecker
on: [push]

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: urlchecker-action
      uses: urlstechie/urlchecker-action@0.0.27
      with:
        # A subfolder or path to navigate to in the present or cloned repository
        subfolder: _posts
        file_types: .md
